'use client';

import { 
  Property, Room, Reservation, Guest, Payment, Task, Alert, User, BilingualText, Language
} from './types';

export const demoProperties: Property[] = [
  {
    id: 'prop_1',
    name: { en: 'Beachfront Resort', es: 'Resort Frente al Mar' },
    description: { en: 'Luxury beachfront resort with ocean views', es: 'Resort de lujo frente al mar con vistas al océano' },
    location: {
      address: '123 Ocean Drive',
      city: 'Miami',
      country: 'USA',
      zipCode: '33139',
      coordinates: { lat: 25.7463, lng: -80.1353 },
    },
    totalRooms: 48,
    amenities: [
      { en: 'Swimming Pool', es: 'Piscina' },
      { en: 'Beach Access', es: 'Acceso a Playa' },
      { en: 'Spa', es: 'Spa' },
      { en: 'Restaurant', es: 'Restaurante' },
      { en: 'WiFi', es: 'WiFi' },
    ],
    maxGuests: 120,
    timezone: 'America/New_York',
    currency: 'USD',
    checkInTime: '15:00',
    checkOutTime: '11:00',
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'prop_2',
    name: { en: 'Mountain Lodge', es: 'Albergue de Montaña' },
    description: { en: 'Cozy mountain retreat with scenic views', es: 'Retiro acogedor en la montaña con vistas panorámicas' },
    location: {
      address: '456 Mountain Road',
      city: 'Aspen',
      country: 'USA',
      zipCode: '81611',
      coordinates: { lat: 39.1911, lng: -106.8175 },
    },
    totalRooms: 32,
    amenities: [
      { en: 'Fireplace', es: 'Chimenea' },
      { en: 'Hiking Trail', es: 'Sendero de Senderismo' },
      { en: 'Hot Tub', es: 'Bañera de Hidromasaje' },
      { en: 'Bar', es: 'Bar' },
    ],
    maxGuests: 85,
    timezone: 'America/Denver',
    currency: 'USD',
    checkInTime: '16:00',
    checkOutTime: '10:00',
    isActive: true,
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date('2024-01-05'),
  },
];

export const demoRooms: Room[] = [
  {
    id: 'room_1',
    propertyId: 'prop_1',
    name: { en: 'Ocean View Suite', es: 'Suite con Vista al Océano' },
    roomNumber: '101',
    type: 'suite',
    capacity: 2,
    bedrooms: 1,
    bathrooms: 1,
    basePrice: 250,
    amenities: [
      { en: 'King Bed', es: 'Cama King' },
      { en: 'Balcony', es: 'Balcón' },
      { en: 'Ocean View', es: 'Vista al Océano' },
    ],
    status: 'available',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'room_2',
    propertyId: 'prop_1',
    name: { en: 'Deluxe Room', es: 'Habitación de Lujo' },
    roomNumber: '102',
    type: 'room',
    capacity: 2,
    bedrooms: 1,
    bathrooms: 1,
    basePrice: 150,
    amenities: [
      { en: 'Queen Bed', es: 'Cama Queen' },
      { en: 'Air Conditioning', es: 'Aire Acondicionado' },
    ],
    status: 'available',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'room_3',
    propertyId: 'prop_2',
    name: { en: 'Mountain Cabin', es: 'Cabaña de Montaña' },
    roomNumber: '201',
    type: 'cabin',
    capacity: 4,
    bedrooms: 2,
    bathrooms: 2,
    basePrice: 200,
    amenities: [
      { en: 'Fireplace', es: 'Chimenea' },
      { en: 'Forest View', es: 'Vista al Bosque' },
      { en: 'Hot Tub', es: 'Bañera de Hidromasaje' },
    ],
    status: 'available',
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date('2024-01-05'),
  },
];

export const demoGuests: Guest[] = [
  {
    id: 'guest_1',
    name: 'John Smith',
    email: 'john@example.com',
    phone: '+1-555-0101',
    nationality: 'USA',
    totalBookings: 5,
    totalSpent: 2500,
    isVIP: true,
    preferredLanguage: 'en',
    preferences: { en: 'Non-smoking room', es: 'Habitación libre de humo' },
    createdAt: new Date('2023-06-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'guest_2',
    name: 'María García',
    email: 'maria@example.com',
    phone: '+34-91-123-4567',
    nationality: 'Spain',
    totalBookings: 3,
    totalSpent: 1200,
    isVIP: false,
    preferredLanguage: 'es',
    preferences: { en: 'Ground floor room', es: 'Habitación en planta baja' },
    createdAt: new Date('2023-08-15'),
    updatedAt: new Date('2024-01-01'),
  },
];

export const demoReservations: Reservation[] = [
  {
    id: 'res_1',
    propertyId: 'prop_1',
    roomId: 'room_1',
    guestId: 'guest_1',
    guestName: 'John Smith',
    guestEmail: 'john@example.com',
    checkInDate: new Date('2024-02-15'),
    checkOutDate: new Date('2024-02-18'),
    source: 'booking.com',
    reservationStatus: 'confirmed',
    paymentStatus: 'partially_paid',
    cleaningStatus: 'ready',
    totalAmount: 750,
    paidAmount: 500,
    balanceDue: 250,
    numberOfGuests: 2,
    specialRequests: { en: 'Late arrival', es: 'Llegada tarde' },
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: 'res_2',
    propertyId: 'prop_1',
    roomId: 'room_2',
    guestId: 'guest_2',
    guestName: 'María García',
    guestEmail: 'maria@example.com',
    checkInDate: new Date('2024-02-20'),
    checkOutDate: new Date('2024-02-25'),
    source: 'airbnb',
    reservationStatus: 'confirmed',
    paymentStatus: 'paid',
    cleaningStatus: 'ready',
    totalAmount: 750,
    paidAmount: 750,
    balanceDue: 0,
    numberOfGuests: 1,
    createdAt: new Date('2024-01-16'),
    updatedAt: new Date('2024-01-16'),
  },
];

export const demoPayments: Payment[] = [
  {
    id: 'pay_1',
    reservationId: 'res_1',
    propertyId: 'prop_1',
    guestId: 'guest_1',
    method: 'credit_card',
    type: 'deposit',
    amount: 500,
    currency: 'USD',
    invoiceNumber: 'INV-001',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
];

export const demoTasks: Task[] = [
  {
    id: 'task_1',
    propertyId: 'prop_1',
    roomId: 'room_1',
    reservationId: 'res_1',
    title: { en: 'Room Cleaning', es: 'Limpieza de Habitación' },
    type: 'cleaning',
    status: 'completed',
    priority: 'high',
    dueDate: new Date('2024-02-15'),
    completedAt: new Date('2024-02-15'),
    createdAt: new Date('2024-02-14'),
    updatedAt: new Date('2024-02-15'),
  },
  {
    id: 'task_2',
    propertyId: 'prop_1',
    roomId: 'room_2',
    title: { en: 'AC Maintenance', es: 'Mantenimiento de Aire Acondicionado' },
    type: 'maintenance',
    status: 'todo',
    priority: 'medium',
    dueDate: new Date('2024-02-28'),
    createdAt: new Date('2024-02-10'),
    updatedAt: new Date('2024-02-10'),
  },
];

export const demoAlerts: Alert[] = [
  {
    id: 'alert_1',
    propertyId: 'prop_1',
    type: 'pending_payment',
    level: 'warning',
    title: { en: 'Pending Payment', es: 'Pago Pendiente' },
    message: { en: 'Reservation RES-001 has a pending balance of $250', es: 'La reservación RES-001 tiene un saldo pendiente de $250' },
    relatedEntity: { type: 'reservation', id: 'res_1' },
    isActive: true,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
];

export const demoData = {
  properties: demoProperties,
  rooms: demoRooms,
  guests: demoGuests,
  reservations: demoReservations,
  payments: demoPayments,
  tasks: demoTasks,
  alerts: demoAlerts,
};
